INSERT INTO industries (name, slug, description) VALUES
('Technology', 'technology', 'Software, hardware, and tech-enabled services'),
('Healthcare', 'healthcare', 'Medical devices, pharmaceuticals, and health services'),
('Fintech', 'fintech', 'Financial technology and services'),
('E-commerce', 'ecommerce', 'Online retail and marketplace platforms'),
('SaaS', 'saas', 'Software as a Service platforms'),
('Artificial Intelligence', 'ai', 'AI and machine learning solutions'),
('Blockchain', 'blockchain', 'Cryptocurrency and blockchain technology'),
('Clean Energy', 'clean-energy', 'Renewable energy and sustainability'),
('EdTech', 'edtech', 'Educational technology and learning platforms'),
('Food & Beverage', 'food-beverage', 'Food production, restaurants, and beverage'),
('Real Estate', 'real-estate', 'Property technology and real estate services'),
('Transportation', 'transportation', 'Logistics, mobility, and transportation'),
('Entertainment', 'entertainment', 'Media, gaming, and entertainment'),
('Agriculture', 'agriculture', 'AgTech and agricultural innovation'),
('Manufacturing', 'manufacturing', 'Industrial and manufacturing technology'),
('Retail', 'retail', 'Physical and omnichannel retail'),
('Cybersecurity', 'cybersecurity', 'Information security and privacy'),
('IoT', 'iot', 'Internet of Things and connected devices'),
('Biotech', 'biotech', 'Biotechnology and life sciences'),
('Consumer Products', 'consumer-products', 'Consumer goods and services');
