<?php

echo "<h1>Setting Up Directory Structure</h1>";

$directories = [
    'storage',
    'storage/cache',
    'storage/logs',
    'storage/sessions',
    'storage/temp',
    'public/uploads',
    'public/uploads/documents',
    'public/uploads/documents/pitch-decks',
    'public/uploads/documents/financials',
    'public/uploads/documents/legal-docs',
    'public/uploads/avatars',
    'public/uploads/company-logos',
    'tests',
    'tests/integration',
    'tests/unit'
];

$files = [
    'storage/logs/.gitkeep' => '',
    'storage/cache/.gitkeep' => '',
    'storage/temp/.gitkeep' => '',
    'public/uploads/.gitkeep' => '',
    'src/Views/dashboard/investor.php' => getInvestorDashboardContent(),
    'src/Views/dashboard/startup.php' => getStartupDashboardContent()
];

echo "<h2>Creating Directories...</h2>";
foreach ($directories as $dir) {
    if (!file_exists($dir)) {
        if (mkdir($dir, 0755, true)) {
            echo "✅ Created directory: $dir<br>";
        } else {
            echo "❌ Failed to create directory: $dir<br>";
        }
    } else {
        echo "✅ Directory already exists: $dir<br>";
    }
}

echo "<h2>Creating Essential Files...</h2>";
foreach ($files as $file => $content) {
    if (!file_exists($file)) {
        $dir = dirname($file);
        if (!file_exists($dir)) {
            mkdir($dir, 0755, true);
        }
        
        if (file_put_contents($file, $content) !== false) {
            echo "✅ Created file: $file<br>";
        } else {
            echo "❌ Failed to create file: $file<br>";
        }
    } else {
        echo "✅ File already exists: $file<br>";
    }
}

echo "<h2>Setting Permissions...</h2>";
$writableDirectories = ['storage', 'public/uploads'];
foreach ($writableDirectories as $dir) {
    if (file_exists($dir)) {
        if (chmod($dir, 0755)) {
            echo "✅ Set permissions for: $dir<br>";
        } else {
            echo "⚠️ Could not set permissions for: $dir<br>";
        }
    }
}

echo "<h2>✅ Directory Setup Complete!</h2>";
echo "<p><a href='debug.php'>Run Debug Script</a> | <a href='dashboard'>Go to Dashboard</a></p>";

function getInvestorDashboardContent() {
    return '<?php
// This file was auto-generated by setup script
// You can customize it as needed

// If this file loads, it means the investor dashboard view is available
if (!isset($user)) {
    echo "<div class=\"alert alert-danger\">User data not available</div>";
    return;
}
?>

<!-- Welcome Section -->
<div class="row mb-4">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <h2 class="card-title">Welcome back, <?= htmlspecialchars($user[\'first_name\'] ?? \'Investor\') ?>!</h2>
                <p class="card-text text-muted">Your investor dashboard</p>
            </div>
        </div>
    </div>
</div>

<!-- Quick Actions -->
<div class="row">
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">
                <h5>Quick Actions</h5>
            </div>
            <div class="card-body">
                <a href="<?= url(\'profile/edit\') ?>" class="btn btn-primary mb-2">Edit Profile</a><br>
                <a href="<?= url(\'search/startups\') ?>" class="btn btn-outline-primary mb-2">Find Startups</a><br>
                <a href="<?= url(\'matches\') ?>" class="btn btn-outline-secondary">View Matches</a>
            </div>
        </div>
    </div>
    
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">
                <h5>Investment Stats</h5>
            </div>
            <div class="card-body">
                <p>Matches: <?= $match_stats[\'total_matches\'] ?? 0 ?></p>
                <p>Mutual Interest: <?= $match_stats[\'mutual_matches\'] ?? 0 ?></p>
                <p>Pending: <?= $match_stats[\'pending_matches\'] ?? 0 ?></p>
            </div>
        </div>
    </div>
</div>';
}

function getStartupDashboardContent() {
    return '<?php
// This file was auto-generated by setup script
// You can customize it as needed

// If this file loads, it means the startup dashboard view is available
if (!isset($user)) {
    echo "<div class=\"alert alert-danger\">User data not available</div>";
    return;
}
?>

<!-- Welcome Section -->
<div class="row mb-4">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <h2 class="card-title">Welcome back, <?= htmlspecialchars($user[\'first_name\'] ?? \'Founder\') ?>!</h2>
                <p class="card-text text-muted">Your startup dashboard</p>
            </div>
        </div>
    </div>
</div>

<!-- Quick Actions -->
<div class="row">
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">
                <h5>Quick Actions</h5>
            </div>
            <div class="card-body">
                <a href="<?= url(\'profile/edit\') ?>" class="btn btn-primary mb-2">Edit Profile</a><br>
                <a href="<?= url(\'search/investors\') ?>" class="btn btn-outline-primary mb-2">Find Investors</a><br>
                <a href="<?= url(\'matches\') ?>" class="btn btn-outline-secondary">View Matches</a>
            </div>
        </div>
    </div>
    
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">
                <h5>Startup Stats</h5>
            </div>
            <div class="card-body">
                <p>Matches: <?= $match_stats[\'total_matches\'] ?? 0 ?></p>
                <p>Mutual Interest: <?= $match_stats[\'mutual_matches\'] ?? 0 ?></p>
                <p>Pending: <?= $match_stats[\'pending_matches\'] ?? 0 ?></p>
            </div>
        </div>
    </div>
</div>';
}
?>